---
- name: Install Java 1.7 and some basic dependencies
  yum: name={{item}} state=present
  with_items:
   - unzip
   - java-1.7.0-openjdk
   - libselinux-python
   - libsemanage-python

- name: Download JBoss from jboss.org
  get_url: url=http://download.jboss.org/jbossas/7.1/jboss-as-7.1.1.Final/jboss-as-7.1.1.Final.zip dest=/opt/jboss-as-7.1.1.Final.zip
  register: result
  #until: result.status_code is not 200
  until: result | success
  retries: 5
  delay: 10
  
- name: Extract archive
  unarchive: dest=/usr/share src=/opt/jboss-as-7.1.1.Final.zip creates=/usr/share/jboss-as copy=no 

  # Rename the dir to avoid encoding the version in the init script
- name: Rename install directory
  command: chdir=/usr/share /bin/mv jboss-as-7.1.1.Final jboss-as creates=/usr/share/jboss-as

- name: Copying standalone.xml configuration file
  template: src=standalone.xml dest=/usr/share/jboss-as/standalone/configuration/
  notify: restart jboss
  
- name: Adding JBoss AP 7 Admin User
  template: src=mgmt-users.properties dest=/usr/share/jboss-as/standalone/configuration/mgmt-users.properties
  notify: restart jboss

- name: Add group "jboss"
  group: name=jboss

- name: Add user "jboss"
  user: name=jboss group=jboss home=/usr/share/jboss-as

- name: Change ownership of JBoss installation
  file: path=/usr/share/jboss-as/ owner=jboss group=jboss state=directory recurse=yes

- name: Copy the init script
  copy: src=jboss-as-standalone.sh dest=/etc/init.d/jboss mode=0755

- name: Workaround for systemd bug
  shell: service jboss start && chkconfig jboss on

- name: Enable JBoss to be started at boot
  service: name=jboss enabled=yes state=started

- name: deploy iptables rules
  template: src=iptables-save dest=/etc/sysconfig/iptables
  when: ansible_distribution_major_version != "7" 
  notify: restart iptables

- name: Ensure that firewalld is installed
  yum: name=firewalld state=present
  when: ansible_distribution_major_version == "7" 

- name: Ensure that firewalld is started
  service: name=firewalld state=started
  when: ansible_distribution_major_version == "7" 

- name: deploy firewalld rules
  firewalld: immediate=yes port={{ item }} state=enabled permanent=yes
  when: ansible_distribution_major_version == "7"
  with_items:
  - "{{ http_port }}/tcp"
  - "{{ https_port }}/tcp"
  - "{{ mgmt_port }}/tcp"
  - "80/tcp"
  - "443/tcp"

- name: redirect 80 port access to {{ http_port }} port
  command: firewall-cmd --permanent --direct --add-rule ipv4 nat PREROUTING 0 -p tcp -m tcp --dport 80 -j REDIRECT --to-ports {{ http_port }}
  notify: restart firewalld
  
- name: redirect 443 port access to {{ https_port }} port
  command: firewall-cmd --permanent --direct --add-rule ipv4 nat PREROUTING 0 -p tcp -m tcp --dport 443 -j REDIRECT --to-ports {{ https_port }}
  notify: restart firewalld
